
<?php if ($this->pageCount > 1): ?>
  
<div class="pagination pagination-centered">
  <ul>
    <?php if (isset($this->previous)): ?>
      <li class="previous">
        <a href="<?php echo $this->url(array('page' => $this->first)); ?>" title="<?php echo $this->t('First'); ?>">
          &laquo;
        </a>
      </li>
    <?php else: ?>
      <li class="disabled previous">
        <a href="#" title="<?php echo $this->t('First'); ?>">
          &laquo;
        </a>
      </li>
    <?php endif; ?>
    
    <?php if (isset($this->previous)): ?>
      <li>
        <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" title="<?php echo $this->t('Prev'); ?>">
          &lsaquo;
        </a>
      </li>
    <?php else: ?>
      <li class="disabled">
        <a href="#" title="<?php echo $this->t('Prev'); ?>">
          &lsaquo;
        </a>
      </li>
    <?php endif; ?>
    
    <?php foreach ($this->pagesInRange as $page): ?>
      
      <?php if ($page != $this->current): ?>
        <li>
          <a href="<?php echo $this->url(array('page' => $page)); ?>">
            <?php echo $page; ?>
          </a>
        </li>
      <?php else: ?>
        <li class="active">
          <a href="#"><?php echo $page; ?></a>
        </li>
      <?php endif; ?>
      
    <?php endforeach; ?>
    
    <?php if (isset($this->next)): ?>
      <li>
        <a href="<?php echo $this->url(array('page' => $this->next)); ?>" title="<?php echo $this->t('Next'); ?>">
          &rsaquo;
        </a>
      </li>
    <?php else: ?>
      <li class="disabled">
        <a href="#" title="<?php echo $this->t('Next'); ?>">
          &rsaquo;
        </a>
      </li>
    <?php endif; ?>
    
    <?php if (isset($this->next)): ?>
      <li>
        <a href="<?php echo $this->url(array('page' => $this->last)); ?>" title=""<?php echo $this->t('Last'); ?>>
          &raquo;
        </a>
      </li>
    <?php else: ?>
      <li class="disabled">
        <a href="#" title=""<?php echo $this->t('Last'); ?>>
          &raquo;
        </a>
      </li>
    <?php endif; ?>
    
  </ul>
</div>
  
<?php endif; ?>
