<?php
/**
 * This file will never be used by controllers.
 * This is used to let translation string extractors (like poedit) detect 
 * and extract strings that need translation
 */


/**
 * Menu
 */
$this->t('Home');
$this->t('Administration');


/**
 * Submenu
 */



/**
 * ACL
 */
$this->t('system:admin');
$this->t('administer');
$this->t('administer system configuration');
$this->t('view system reports');



