<?php
// add sidebar
//$this->placeholder('layout-sidebar')->captureStart();
//echo $this->partial('admin/users/index-sidebar.phtml', array('administer' => $administer));
//$this->placeholder('layout-sidebar')->captureEnd();
?>

<div class="btn-toolbar" style="margin-bottom: 9px">
  
    <div class="btn-group">
      <a class="btn btn-inverse" href="<?php echo $this->url(array('action' => 'add')); ?>">
        <i class="icon-plus icon-white"></i>
        <?php echo $this->t('Add Group'); ?>
      </a>
    </div>

    <p class="pull-right">
      <?php echo $this->paginationCount($this->groups); ?>
    </p>
</div>
 
<?php if(count($this->groups)): ?>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th><?php echo $this->t('Name'); ?></th>
        <th><?php echo $this->t('Number of users'); ?></th>
        <th class="span2"><?php echo $this->t('Actions'); ?></th>
      </tr>
    </thead>
    
    <tbody>
      <?php foreach($this->groups AS $group): ?>
        <tr>
          <td><?php echo $this->escape($group->name); ?></td>
          <td>
            <?php $count = $group->getUserCount(); ?>
            <?php echo $count; ?>
            <?php if($count && $this->acl()->isUserAllowed('user:admin', 'administer users')): ?>
              (<a href="<?php echo $this->url(array('controller' => 'users', 'groups' => $group->id), 'admin'); ?>"><?php echo $this->t('view users'); ?></a>)
            <?php endif; ?>
          </td>
          <td>
            <div class="btn-group">
              <a class="btn" href="<?php echo $this->url(array('action' => 'edit', 'id' => $group->id)); ?>">
                <i class="icon-pencil"></i>
                <?php echo $this->t('Edit'); ?>
              </a>
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $group->id)); ?>">
                    <i class="icon-trash"></i>
                    <?php echo $this->t('Delete'); ?>
                  </a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
  
  <?php echo $this->paginationControl($this->groups, 'Sliding'); ?>
  
<?php endif; ?>
