<?php
$administer = $this->acl()->isUserAllowed('user:admin:groups', 'administer');

// add sidebar
//$this->placeholder('layout-sidebar')->captureStart();
//echo $this->partial('admin/users/index-sidebar.phtml', array('administer' => $administer));
//$this->placeholder('layout-sidebar')->captureEnd();
?>

<?php if($administer): ?>
  <div class="btn-toolbar" style="margin-bottom: 9px">
    
      <div class="btn-group">
        <a class="btn btn-inverse" href="<?php echo $this->url(array('action' => 'add')); ?>">
          <i class="icon-plus icon-white"></i>
          <?php echo $this->t('Add group'); ?>
        </a>
      </div>
  
      <p class="pull-right">
        <?php echo $this->paginationCount($this->groups); ?>
      </p>
  </div>
<?php endif; ?>
    
 
<?php if(count($this->groups)): ?>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th><?php echo $this->t('Name'); ?></th>
        <th><?php echo $this->t('Number of users'); ?></th>
        <th class="span2"><?php echo $this->t('Actions'); ?></th>
      </tr>
    </thead>
    
    <tbody>
      <?php foreach($this->groups AS $group): ?>
        <tr>
          <td><?php echo $this->escape($group->name); ?></td>
          <td>
            <?php echo $group->getUserCount(); ?>
            <?php if($this->acl()->isUserAllowed('user:admin:users', 'view')): ?>
              (<a href="<?php echo $this->url(array('controller' => 'users', 'groups' => $group->id), 'admin'); ?>"><?php echo $this->t('view users'); ?></a>)
            <?php endif; ?>
          </td>
          <td>
            <?php if($administer): ?>
              <div class="btn-group">
                <a class="btn" href="<?php echo $this->url(array('action' => 'edit', 'id' => $group->id)); ?>">
                  <i class="icon-pencil"></i>
                  <?php echo $this->t('Edit'); ?>
                </a>
              </div>
            <?php endif; ?>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
  
  <?php echo $this->paginationControl($this->groups, 'Sliding'); ?>
  
<?php endif; ?>
