<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php echo $this->message ?></title>
</head>
<body>
  <section>
    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>
  </section>
  
<?php if ($this->errorsShow): ?>
  
  <hr />
  
  <section>
  
    <h1>Debug info</h1>

    <h3>Exception information</h3>
    <table class="table table-striped table-condensed">
      <tbody>
        <tr>
            <th class="span2">Type</th>
            <td><?php echo $this->exceptionType; ?></td>
        </tr>
        <tr>
            <th>Message</th>
            <td><?php echo $this->exceptionMessage; ?></td>
        </tr>
      <tbody>
    </table>


    <h3>Request Parameters</h3>
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>Parameter</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach($this->requestParameters AS $param => $value): ?>
        <tr>
          <th><?php echo $this->escape($param); ?></th>
          <td><?php echo $value; ?></td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>


    <h3>Backtrace</h3>
    <table class="table table-striped table-condensed">
      <thead>
        <tr>
          <th>#</th>
          <th>Function / Location</th>
        </tr>
      </thead>
      <tbody>
      <?php foreach($this->exceptionTrace AS $trace): ?>
        <tr>
          <th><?php echo $trace['#']; ?></th>
          <td>
              <?php echo $trace['function']; ?><br />
              <?php echo $trace['location']; ?>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>

  </section>
  

<?php endif ?>

</body>
</html>
