<?php
// Extract the menus
$primary = $this->navigation()->findById('primary-navigation');
$account = $this->navigation()->findById('secondary-navigation');
?>

<div class="topbar-wrapper" style="z-index: 5;">
    <div class="topbar" id="topbar" data-dropdown="dropdown"><div class="topbar-inner">
        <div class="container-fluid">
            <h3><a href="#">Project Name</a></h3>
            <?php echo $this->partial('_menu.phtml', array('page' => $primary, 'class' => 'nav primary-nav')); ?>
            <?php echo $this->partial('_menu.phtml', array('page' => $account, 'class' => 'nav secondary-nav')); ?>
        </div>
    </div></div>
</div>
