<?php
/**
 * Renders a menu item & its children
 * 
 * Variables:
 * 
 * $this->page (Zend_Navigation_Page)
 *     The page to render
 */

// add the current language to the page
$this->page->setParams(array(
    'language' => Zend_Controller_Front::getInstance()->getRequest()->getParam('language')
));
 
// "preprocess"
$liClass = array();
$aClass  = array();
$aExtra  = NULL;
$aHref   = $this->page->getHref();
$aLabel  = $this->page->getLabel();

if($this->page->isActive()) {
  $liClass[] = 'active';
}

if($this->page->hasChildren()) {
  $liClass[] = 'dropdown';
  $aClass[]  = 'dropdown-toggle';
  $aExtra    = '<b class="caret"></b>';
  $aHref     = '#';
  
  $this->page->setTarget('#');
  $this->page->setClass('dropdown-toggle');
}

$liClass = (count($liClass)) ? ' class="' . implode(' ', $liClass) . '"' : null;
$aClass  = (count($aClass))  ? ' class="' . implode(' ', $aClass)  . '"' : null;
?>

<li<?php echo $liClass; ?>>
    <a href="<?php echo $aHref; ?>"<?php echo $aClass; ?>><?php echo $aLabel; ?><?php echo $aExtra; ?></a>
    <?php if($this->page->hasChildren()): ?>
        <?php echo $this->partial('_menu.phtml', array('page' => $this->page, 'class' => 'dropdown-menu')); ?>
    <?php endif; ?>
</li>
