<?php
/**
 * Renders a menu
 * 
 * Variables:
 * 
 * $this->page (Zend_Navigation_Page)
 *     The page to render
 * $this->class (string)
 *     Optional class for the menu
 */

// menu class
$class = (!empty($this->class)) ? ' class="' . $this->class . '"' : null;
$urlLogin = $this->url(array(
    'module'     => 'user',
    'controller' => 'login',
    'action'     => 'index',
), 'default');

 
// this menu is only for authenticated users
if(!$this->auth()->hasIdentity()):
?>

<ul<?php echo $class; ?>>
    <li>
        <a href="<?php echo $urlLogin; ?>">
            <?php echo $this->t('Login'); ?>
        </a>
    </li>
</ul>

<?php
return;
endif;


 
// Are there items in the menu
if(empty($this->page) || !$this->page->hasChildren()) {
    return;
}



$username = $this->escape($this->user()->username);

// @TODO $this->page->current() not working :(
foreach($this->page AS $page) {
    break;
}

?>

<ul<?php echo $class; ?>>
    <li class="account dropdown">
        <a href="#" class="dropdown-toggle">
            <?php echo $username; ?><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <span class="icon account"></span>
            <?php
                foreach($page AS $child) {
                    echo $this->partial('_menu_item.phtml', array('page' => $child));
                }
            ?>  
            </ul>
    </li>
</ul>
