<?php
/**
 * Renders a menu
 * 
 * Variables:
 * 
 * $this->page (Zend_Navigation_Page)
 *     The page to render
 * $this->class (string)
 *     Optional class for the menu
 */

// menu class
$class = (!empty($this->class)) ? ' class="' . $this->class . '"' : null;
$urlLogin = $this->url(array(
    'module'     => 'user',
    'controller' => 'login',
    'action'     => 'index',
), 'default');

 
// this menu is only for authenticated users
if(!$this->auth()->hasIdentity()):
?>

<ul<?php echo $class; ?>>
    <li>
        <a href="<?php echo $urlLogin; ?>">
            <?php echo $this->t('Login'); ?>
        </a>
    </li>
</ul>

<?php
return;
endif;


 
// Are there items in the menu
if(empty($this->page) || !$this->page->hasChildren()) {
    return;
}


// set the current username as account menu label
$username = $this->escape($this->user()->username);
$this->page->setLabel($username);

echo $this->partial('_menu.phtml', array('page' => $this->page, 'class' => $this->class));
