<?php
/**
 * Defaut layout with menu & sidebar
 * 
 * Based on the fantastic Twitter Bootstrap project!
 */
?>


<?php echo $this->partial('_header.phtml'); ?>

<?php echo $this->partial('_header_menu.phtml'); ?>



<!-- CONTENT -->
  <div class="container-fluid">
    
    <div class="sidebar">
      <div class="well">
          <h5>Sidebar</h5>
          <ul>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
          <h5>Sidebar</h5>
          <ul>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
          <h5>Sidebar</h5>
          <ul>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
        </div>
    </div>
    
    <div class="content">
        <section id="main">
            <div class="page-header">
                <h1>Test the page header</h1>
            </div>
            
            <?php echo $this->layout()->content; ?> 
            
        </section>  
    </div>
    
  </div>
<!-- /CONTENT -->



<!-- FOOTER -->
<footer class="footer">
    <div class="container-fluid ">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>
            powered by <a href="http://sgrame.org">openSGrame</a>
        </p>
    </div>
</footer>
<!-- /FOOTER -->



<?php echo $this->partial('_footer.phtml'); ?>