<?php
/**
 * Renders a menu item & its children
 * 
 * Variables:
 * 
 * $this->page (Zend_Navigation_Page)
 *     The page to render
 */

// check access
if(!$this->navigation()->accept($this->page)) {
    return;
}

// add the current language to the page
$params = $this->page->getParams();
if(!isset($params['language'])) {
    $params['language'] = Zend_Controller_Front::getInstance()
                                                 ->getRequest()
                                                 ->getParam('language');
    $this->page->setParams($params);
}

// "preprocess"
$liClass    = array();
$aClass     = array();
$aExtra     = NULL;
$dataToggle = NULL;
$aHref      = $this->page->getHref();
$aLabel     = $this->t($this->page->getLabel());

if($this->page->isActive()) {
  $router = Zend_Controller_Front::getInstance()->getRouter();
  if ($this->page->getRoute() === $router->getCurrentRouteName()) {
    $liClass[] = 'active';
  }
}

if($this->page->hasChildren()) {
  $liClass[]  = 'dropdown';
  $aClass[]   = 'dropdown-toggle';
  $dataToggle = ' data-toggle="dropdown"';
  $aExtra     = '<b class="caret"></b>';
  $aHref      = '#';
  
  $this->page->setTarget('#');
  $this->page->setClass('dropdown-toggle');
}

$liClass = (count($liClass)) ? ' class="' . implode(' ', $liClass) . '"' : null;
$aClass  = (count($aClass))  ? ' class="' . implode(' ', $aClass)  . '"' : null;
?>

<li<?php echo $liClass; ?>>
    <a href="<?php echo $aHref; ?>"<?php echo $aClass; ?><?php echo $dataToggle; ?>><?php echo $aLabel; ?><?php echo $aExtra; ?></a>
    <?php if($this->page->hasChildren()): ?>
        <?php echo $this->partial('_menu.phtml', array('page' => $this->page, 'class' => 'dropdown-menu')); ?>
    <?php endif; ?>
</li>
