<?php
/**
 * Basic layout
 */
?>


<?php echo $this->partial('_html_header.phtml', array('bodyClass' => array('layout-basic'))); ?>

<div class="content">
    <section id="main">
        <?php if(!empty($this->layout()->title)): ?>
            <div class="page-header">
                <h1><?php echo $this->layout()->title; ?></h1>
            </div>
        <?php endif; ?>
            
        <?php echo $this->layout()->content; ?> 
            
    </section>  
</div>
    
<?php echo $this->render('_html_footer.phtml'); ?>
