<?php
/**
 * Defaut layout with menu & sidebar
 * 
 * Based on the fantastic Twitter Bootstrap project!
 */
?>


<?php echo $this->partial('_html_header.phtml', array('bodyClass' => array('layout-default'))); ?>

<?php echo $this->render('_header_menu.phtml'); ?>

<div class="container-fluid">
  <?php echo $this->render('_header_tabs.phtml'); ?>
  <?php echo $this->render('_header_title.phtml'); ?>
</div>



<!-- CONTENT -->
  <div class="container-fluid">
    
    <!--div class="sidebar">
      <div class="well">
          <h5>Sidebar</h5>
          <ul>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
          <h5>Sidebar</h5>
          <ul>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
          <h5>Sidebar</h5>
          <ul>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
          </ul>
        </div>
    </div-->
    
    <div class="content">
        <section id="main">
        <?php echo $this->render('_messages.phtml'); ?>
          
        
            
            <?php echo $this->layout()->content; ?> 
            
        </section>  
    </div>
    
  </div>
<!-- /CONTENT -->



<?php echo $this->render('_footer.phtml'); ?>
<?php echo $this->render('_html_footer.phtml'); ?>
