<?php
// add sidebar
$this->placeholder('layout-sidebar')->captureStart();
echo $this->partial('admin/users/index-sidebar.phtml', array('searchForm' => $this->searchForm));
$this->placeholder('layout-sidebar')->captureEnd();
?>

<div class="btn-toolbar" style="margin-bottom: 9px">
    <div class="btn-group">
      <a class="btn btn-inverse" href="<?php echo $this->url(array('action' => 'add')); ?>">
        <i class="icon-plus icon-white"></i>
        <?php echo $this->t('Add User'); ?>
      </a>
    </div>

    <p class="pull-right pagination-count">
      <?php echo $this->paginationCount($this->users); ?>
    </p>
</div>
    
 
<?php if(count($this->users)): ?>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th><?php echo $this->t('Username'); ?></th>
        <th><?php echo $this->t('Email'); ?></th>
        <th><?php echo $this->t('Group(s)'); ?></th>
        <th><?php echo $this->t('Role(s)'); ?></th>
        <th class="span2"><?php echo $this->t('Status'); ?></th>
        <th class="span2"><?php echo $this->t('Actions'); ?></th>
      </tr>
    </thead>
    
    <tbody>
      <?php foreach($this->users AS $user): ?>
        <tr>
          <td><?php echo $this->escape($user->username); ?></td>
          <td><?php echo $this->escape($user->email); ?></td>
          <td>
            <?php echo implode(', ', $user->getGroupNames()); ?>
          </td>
          <td>
            <?php echo implode(', ', $user->getRoleNames()); ?>
          </td>
          <td>
            <?php if($user->isActive()): ?>
              <a class="label label-success" href="<?php echo $this->url(array('action' => 'block', 'id' => $user->id)); ?>" title="<?php echo $this->t('Block user'); ?>">
                <?php echo $this->t('Active'); ?>
              </a>
            <?php endif; ?>
            <?php if($user->isBlocked()): ?>
              <a class="label label-important" href="<?php echo $this->url(array('action' => 'activate', 'id' => $user->id)); ?>" title="<?php echo $this->t('Activate user'); ?>">
                <?php echo $this->t('Blocked'); ?>
              </a>
            <?php endif; ?>
            <?php if($user->isLocked()): ?>
              <a class="label label-important" href="<?php echo $this->url(array('action' => 'unlock', 'id' => $user->id)); ?>" title="<?php echo $this->t('Unlock user'); ?>">
                <?php echo $this->t('Locked'); ?>
              </a>
            <?php endif; ?>
          </td>
          <td>
            <div class="btn-group">
              <a class="btn" href="<?php echo $this->url(array('action' => 'edit', 'id' => $user->id)); ?>">
                <i class="icon-pencil"></i>
                <?php echo $this->t('Edit'); ?>
              </a>
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <?php if($user->isBlocked()): ?>
                    <a href="<?php echo $this->url(array('action' => 'activate', 'id' => $user->id)); ?>">
                      <i class="icon-ok-circle"></i>
                      <?php echo $this->t('Activate'); ?>
                    </a>
                  <?php else: ?>
                    <a href="<?php echo $this->url(array('action' => 'block', 'id' => $user->id)); ?>">
                      <i class="icon-ban-circle"></i>
                      <?php echo $this->t('Block'); ?>
                    </a>
                  <?php endif; ?>
                </li>
                <li class="divider"></li>
                <li>
                  <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $user->id)); ?>">
                    <i class="icon-trash"></i>
                    <?php echo $this->t('Delete'); ?>
                  </a>
                </li>
              </ul>
            </div>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
  
  <?php echo $this->paginationControl($this->users, 'Sliding'); ?>
  
<?php endif; ?>