<?php
/**
 * This file will never be used by controllers.
 * This is used to let translation string extractors (like poedit) detect 
 * and extract strings that need translation
 */


/**
 * Menu
 */
$this->t('User');
$this->t('Users');
$this->t('account');
$this->t('Profile');

/**
 * Submenu
 */
$this->t('View Profile');
$this->t('Change password');
$this->t('Logout');
$this->t('Users');
$this->t('Groups');
$this->t('Roles');
$this->t('Permissions');
$this->t('Configuration');



/**
 * ACL
 */
$this->t('cancel own profile');
$this->t('edit profile');
$this->t('register');

$this->t('user:admin');
$this->t('administer all users');
$this->t('administer configuration');
$this->t('administer groups');
$this->t('administer permissions');
$this->t('administer roles');
$this->t('administer users');
$this->t('administer users of same group');
$this->t('administer users of the system');

$this->t('Permission');
$this->t('everyone');
$this->t('registered');
$this->t('admin');


